@startuml
Browser -> Server: Request
activate Server

Server -> "API A":
activate "API A"
Server <-- "API A":
deactivate "API A"

Server -> "API B":
activate "API B"
Server <-- "API B":
deactivate "API B"

Browser <-- Server: Response
deactivate Server
@enduml